function bias = bias_3link(in1,in2)
%BIAS_3LINK
%    BIAS = BIAS_3LINK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Nov-2025 18:14:43

dq3 = in2(3,:);
dq4 = in2(4,:);
dq5 = in2(5,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = sin(q3);
t3 = sin(q5);
t4 = q3+q4;
t5 = cos(t4);
t6 = q5+t4;
t7 = sin(t4);
t12 = (dq3.*t3)./2.5e+1;
t13 = (dq4.*t3)./2.5e+1;
t14 = (dq5.*t3)./2.5e+1;
t17 = dq3.*dq5.*t3.*(-1.0./2.5e+1);
t18 = dq4.*dq5.*t3.*(-1.0./2.5e+1);
t8 = cos(t6);
t9 = sin(t6);
t10 = t5.*(2.0./5.0);
t11 = t7.*(2.0./5.0);
t23 = t7.*(9.81e+2./2.5e+2);
t25 = t12+t13;
t19 = t8./1.0e+1;
t20 = t9./1.0e+1;
t24 = t9.*(9.81e+2./1.0e+3);
t30 = t14+t25;
t21 = dq5.*t19;
t22 = dq5.*t20;
t26 = t10+t19;
t27 = t11+t20;
t31 = dq5.*t30;
t28 = dq4.*t26;
t29 = dq4.*t27;
t32 = -t31;
bias = [dq5.*(t22+dq3.*t20+dq4.*t20)+dq4.*(t22+t29+dq3.*t27)+dq3.*(t22+t29-dq3.*(t2.*2.0-t27));dq5.*(t21+dq3.*t19+dq4.*t19)+dq4.*(t21+t28+dq3.*t26)+dq3.*(t21+t28+dq3.*(t26-cos(q3).*2.0))+1.12815e+2;t2.*(-9.81e+2./5.0e+1)+t17+t18+t23+t24+t32;t17+t18+t23+t24+t32;t24+dq3.*t25+dq4.*t25];
end
