function Jf = dFK_dq_foot(in1)
%dFK_dq_foot
%    Jf = dFK_dq_foot(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Nov-2025 18:14:42

q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = sin(q3);
t6 = sin(q4);
t7 = sin(q5);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t8.*(2.0./5.0);
t14 = t9.*(2.0./5.0);
t15 = t10.*(2.0./5.0);
t16 = t11.*(2.0./5.0);
t18 = t9+t10;
t17 = -t13;
t19 = t8+t12;
t20 = t4.*t18.*(2.0./5.0);
t21 = t7.*t18.*(2.0./5.0);
t22 = t4.*t19.*(2.0./5.0);
t23 = t7.*t19.*(2.0./5.0);
t24 = -t22;
t25 = t14+t15+t20+t23;
t26 = t16+t17+t21+t24;
Jf = reshape([1.0,0.0,0.0,1.0,t26,t25,t26,t25,t21+t24,t20+t23],[2,5]);
end
