function H = H_3link(in1)
%H_3link
%    H = H_3link(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Nov-2025 18:14:43

q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q3);
t3 = cos(q5);
t4 = sin(q3);
t5 = q3+q4;
t6 = t2.*2.0;
t7 = t4.*2.0;
t8 = cos(t5);
t9 = q5+t5;
t10 = sin(t5);
t14 = t3./2.5e+1;
t15 = t3.*(2.0./2.5e+1);
t11 = cos(t9);
t12 = sin(t9);
t13 = -t7;
t16 = t8.*(2.0./5.0);
t17 = t10.*(2.0./5.0);
t22 = t14+1.0./4.0e+1;
t23 = t15+3.1e+1./2.0e+2;
t18 = -t16;
t19 = t11./1.0e+1;
t20 = t12./1.0e+1;
t21 = -t19;
t24 = t17+t20;
t25 = t18+t21;
t26 = t13+t24;
t27 = t6+t25;
H = reshape([2.3e+1./2.0,0.0,t27,t25,t21,0.0,2.3e+1./2.0,t26,t24,t20,t27,t26,t15+1.21e+2./2.0e+2,t23,t22,t25,t24,t23,t23,t22,t21,t20,t22,t22,1.0./4.0e+1],[5,5]);
end
