function J_lf = dFK_lf_dq(in1)
%dFK_lf_dq
%    J_lf = dFK_lf_dq(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    08-Nov-2025 13:26:11

q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = cos(q3);
t3 = cos(q6);
t4 = cos(q7);
t5 = sin(q3);
t6 = sin(q6);
t7 = sin(q7);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t8.*(2.0./5.0);
t14 = t9.*(2.0./5.0);
t15 = t10.*(2.0./5.0);
t16 = t11.*(2.0./5.0);
t18 = t9+t10;
t17 = -t13;
t19 = t8+t12;
t20 = t4.*t18.*(2.0./5.0);
t21 = t7.*t18.*(2.0./5.0);
t22 = t4.*t19.*(2.0./5.0);
t23 = t7.*t19.*(2.0./5.0);
t24 = -t22;
t25 = t14+t15+t20+t23;
t26 = t16+t17+t21+t24;
J_lf = reshape([1.0,0.0,0.0,1.0,t26,t25,0.0,0.0,0.0,0.0,t26,t25,t21+t24,t20+t23],[2,7]);
end
