function p_lf = FK_lf(in1)
%FK_lf
%    P_LF = FK_lf(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    08-Nov-2025 13:26:11

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = cos(q3);
t3 = cos(q6);
t4 = cos(q7);
t5 = sin(q3);
t6 = sin(q6);
t7 = sin(q7);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
p_lf = [q1-t9.*(2.0./5.0)-t10.*(2.0./5.0)-t4.*t13.*(2.0./5.0)-t7.*t14.*(2.0./5.0);q2-t8.*(2.0./5.0)+t11.*(2.0./5.0)-t4.*t14.*(2.0./5.0)+t7.*t13.*(2.0./5.0)];
end
