function dJ_lf_dt = Jc_dot_lf_func(in1,in2)
%Jc_dot_lf_func
%    dJ_lf_dt = Jc_dot_lf_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    08-Nov-2025 13:26:12

dq3 = in2(3,:);
q3 = in1(3,:);
q6 = in1(6,:);
q7 = in1(7,:);
t2 = cos(q3);
t3 = cos(q6);
t4 = cos(q7);
t5 = sin(q3);
t6 = sin(q6);
t7 = sin(q7);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t8.*(2.0./5.0);
t14 = t9.*(2.0./5.0);
t15 = t10.*(2.0./5.0);
t16 = t11.*(2.0./5.0);
t18 = t9+t10;
t17 = -t16;
t19 = t8+t12;
t20 = t4.*t18.*(2.0./5.0);
t21 = t7.*t18.*(2.0./5.0);
t22 = -t21;
t23 = t4.*t19.*(2.0./5.0);
t24 = t7.*t19.*(2.0./5.0);
t25 = t14+t15+t20+t24;
t26 = t13+t17+t22+t23;
t27 = dq3.*t25;
t28 = dq3.*t26;
dJ_lf_dt = reshape([0.0,0.0,0.0,0.0,t27,t28,0.0,0.0,0.0,0.0,t27,t28,dq3.*(t20+t24),-dq3.*(t21-t23)],[2,7]);
end
