function dJ_rf_dt = Jc_dot_rf_func(in1,in2)
%Jc_dot_rf_func
%    dJ_rf_dt = Jc_dot_rf_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    08-Nov-2025 13:26:11

dq3 = in2(3,:);
dq4 = in2(4,:);
dq5 = in2(5,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = sin(q3);
t6 = sin(q4);
t7 = sin(q5);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t8.*(2.0./5.0);
t14 = t9.*(2.0./5.0);
t15 = t10.*(2.0./5.0);
t16 = t11.*(2.0./5.0);
t18 = t9+t10;
t17 = -t16;
t19 = t8+t12;
t20 = t4.*t18.*(2.0./5.0);
t21 = t7.*t18.*(2.0./5.0);
t22 = -t21;
t23 = t4.*t19.*(2.0./5.0);
t24 = t7.*t19.*(2.0./5.0);
t25 = t20+t24;
t26 = t22+t23;
t28 = -dq5.*(t21-t23);
t27 = dq5.*t25;
t29 = t14+t15+t25;
t30 = t13+t17+t26;
t31 = dq3.*t29;
t32 = dq4.*t29;
t33 = dq3.*t30;
t34 = dq4.*t30;
t35 = t27+t31+t32;
t36 = t28+t33+t34;
dJ_rf_dt = reshape([0.0,0.0,0.0,0.0,t35,t36,t35,t36,t27+dq3.*t25+dq4.*t25,t28-dq3.*(t21-t23)-dq4.*(t21-t23),0.0,0.0,0.0,0.0],[2,7]);
end
