function J_ee = fcn_J_ee(in1,in2)
%fcn_J_ee
%    J_ee = fcn_J_ee(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    08-Oct-2025 22:44:12

l2 = in2(2,:);
l3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q2+q3;
t7 = l2.*t3;
t8 = cos(t6);
t9 = l2.*t5;
t10 = sin(t6);
t11 = l3.*t8;
t12 = l3.*t10;
t13 = -t12;
t14 = t7+t11;
t15 = t9+t12;
J_ee = reshape([-t4.*t15,t2.*t15,0.0,t2.*t14,t4.*t14,-t9+t13,t2.*t11,t4.*t11,t13],[3,3]);
end
