function pos_ee_htm = fcn_pos_ee(in1,in2)
%FCN_POS_EE
%    POS_EE_HTM = FCN_POS_EE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    08-Oct-2025 22:44:12

l1 = in2(1,:);
l2 = in2(2,:);
l3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q2);
t3 = q2+q3;
t4 = l2.*t2;
t5 = sin(t3);
t6 = l3.*t5;
t7 = t4+t6;
pos_ee_htm = [t7.*cos(q1);t7.*sin(q1);l1+l2.*cos(q2)+l3.*cos(t3)];
end
