function vel_ee = fcn_vel_ee(in1,in2,in3)
%FCN_VEL_EE
%    VEL_EE = FCN_VEL_EE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    08-Oct-2025 22:44:12

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
l2 = in3(2,:);
l3 = in3(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = q2+q3;
t7 = l2.*t3;
t8 = cos(t6);
t9 = l2.*t5;
t10 = sin(t6);
t11 = l3.*t8;
t12 = l3.*t10;
t13 = t7+t11;
t14 = t9+t12;
vel_ee = [dq3.*t2.*t11+dq2.*t2.*t13-dq1.*t4.*t14;dq1.*t2.*t14+dq3.*t4.*t11+dq2.*t4.*t13;-dq3.*t12-dq2.*t14];
end
