function [f,grad,Hess] = fcn_f_grad_Hess(x1,x2)
%fcn_f_grad_Hess
%    [F,GRAD,Hess] = fcn_f_grad_Hess(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Oct-2025 23:29:08

t2 = x2.*3.0;
t3 = -x1;
t4 = -t2;
t5 = t3-1.0./1.0e+1;
t6 = t2+x1-1.0./1.0e+1;
t7 = exp(t6);
t8 = exp(t5);
t9 = t4+x1-1.0./1.0e+1;
t10 = exp(t9);
t11 = t7.*3.0;
t12 = t10.*3.0;
t15 = t7+t8+t10;
f = t15;
if nargout > 1
    t13 = -t12;
    t14 = t11+t13;
    grad = [t7-t8+t10;t14];
end
if nargout > 2
    Hess = reshape([t15,t14,t14,t7.*9.0+t10.*9.0],[2,2]);
end
end
