function [fi,grad_ineq,Hess_ineq] = fcn_ineq_grad_Hess(in1,t)
%fcn_ineq_grad_Hess
%    [FI,GRAD_INEQ,Hess_ineq] = fcn_ineq_grad_Hess(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    29-Oct-2025 23:29:08

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1.^2;
t3 = -x2;
t4 = t2./2.0;
t5 = t3+t4+1.0./1.0e+1;
fi = t5;
if nargout > 1
    t6 = 1.0./t5;
    t7 = t6.^2;
    t8 = t.*t6;
    grad_ineq = [-t8.*x1;t8];
end
if nargout > 2
    t9 = t.*t7.*x1;
    t10 = -t9;
    Hess_ineq = reshape([-t8+t.*t2.*t7,t10,t10,t.*t7],[2,2]);
end
end
